version: '3.8'
services:
  node:
    image: ghcr.io/openethereum/sbc-lighthouse:v2.0.1-sbc
    command: |
      lighthouse beacon_node
      --testnet-dir /root/sbc/config
      --discovery-port 12000
      --enr-udp-port 12000
      --port 13000
      --eth1-endpoints $XDAI_RPC_URL
      --datadir /home/.eth2/beaconchaindata
      --enr-address $PUBLIC_IP
      --http-address 0.0.0.0
      --http
      --debug-level $LOG_LEVEL
    ports:
      - '12000:12000/udp'
      - '13000:13000'
      - '127.0.0.1:5052:5052'
    volumes:
      - ./config:/root/sbc/config
      - ./node_db:/home/.eth2/beaconchaindata
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
  node-private-slasher:
    image: ghcr.io/openethereum/sbc-lighthouse:v2.0.1-sbc
    command: |
      lighthouse beacon_node
      --testnet-dir /root/sbc/config
      --discovery-port 12000
      --enr-udp-port 12000
      --port 13000
      --eth1-endpoints $XDAI_RPC_URL
      --datadir /home/.eth2/beaconchaindata
      --slasher-dir /home/.eth2/slasherdata
      --enr-address $PUBLIC_IP
      --http-address 0.0.0.0
      --http
      --debug-level $LOG_LEVEL
      --slasher
      --slasher-max-db-size 32
    ports:
      - '12000:12000/udp'
      - '13000:13000'
      - '127.0.0.1:5052:5052'
    volumes:
      - ./config:/root/sbc/config
      - ./node_db:/home/.eth2/beaconchaindata
      - ./slasher_db:/home/.eth2/slasherdata
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
  node-public-slasher:
    image: ghcr.io/openethereum/sbc-lighthouse:v2.0.1-sbc
    command: |
      lighthouse beacon_node
      --testnet-dir /root/sbc/config
      --discovery-port 12000
      --enr-udp-port 12000
      --port 13000
      --eth1-endpoints $XDAI_RPC_URL
      --datadir /home/.eth2/beaconchaindata
      --slasher-dir /home/.eth2/slasherdata
      --enr-address $PUBLIC_IP
      --http-address 0.0.0.0
      --http
      --debug-level $LOG_LEVEL
      --slasher
      --slasher-max-db-size 32
      --slasher-broadcast
    ports:
      - '12000:12000/udp'
      - '13000:13000'
      - '127.0.0.1:5052:5052'
    volumes:
      - ./config:/root/sbc/config
      - ./node_db:/home/.eth2/beaconchaindata
      - ./slasher_db:/home/.eth2/slasherdata
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
  validator-import:
    image: ghcr.io/openethereum/sbc-lighthouse:v2.0.1-sbc
    command: |
      lighthouse account_manager validator import
      --testnet-dir /root/sbc/config
      --password-file /root/sbc/keys/keystore_password.txt
      --reuse-password
      --directory /root/sbc/keys/validator_keys
      --datadir /root/sbc
    volumes:
      - ./config:/root/sbc/config
      - ./keys:/root/sbc/keys
      - ./validators:/root/sbc/validators
  validator:
    image: ghcr.io/openethereum/sbc-lighthouse:v2.0.1-sbc
    command: |
      lighthouse validator_client
      --testnet-dir /root/sbc/config
      --validators-dir /root/sbc/validators
      --beacon-nodes http://node:5052
    volumes:
      - ./config:/root/sbc/config
      - ./validators:/root/sbc/validators
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
