version: '3.8'
services:
  node:
    image: ghcr.io/gnosischain/gbc-lighthouse:latest-unstable
    command: |
      lighthouse beacon_node
      --testnet-dir /root/sbc/config
      --discovery-port 12000
      --port 13000
      --eth1-endpoints $XDAI_RPC_URL
      --datadir /home/.eth2/beaconchaindata
      --http-address 127.0.0.1
      --http
      --enr-address $PUBLIC_IP
      --enr-udp-port 12000
      --debug-level $LOG_LEVEL
    network_mode: host
    volumes:
      - ./config:/root/sbc/config
      - ./node_db:/home/.eth2/beaconchaindata
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
  node-private-slasher:
    image: ghcr.io/gnosischain/gbc-lighthouse:latest-unstable
    command: |
      lighthouse beacon_node
      --testnet-dir /root/sbc/config
      --discovery-port 12000
      --port 13000
      --eth1-endpoints $XDAI_RPC_URL
      --datadir /home/.eth2/beaconchaindata
      --slasher-dir /home/.eth2/slasherdata
      --http-address 127.0.0.1
      --http
      --debug-level $LOG_LEVEL
      --slasher
      --slasher-max-db-size 32
    network_mode: host
    volumes:
      - ./config:/root/sbc/config
      - ./node_db:/home/.eth2/beaconchaindata
      - ./slasher_db:/home/.eth2/slasherdata
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
  node-public-slasher:
    image: ghcr.io/gnosischain/gbc-lighthouse:latest-unstable
    command: |
      lighthouse beacon_node
      --testnet-dir /root/sbc/config
      --discovery-port 12000
      --port 13000
      --eth1-endpoints $XDAI_RPC_URL
      --datadir /home/.eth2/beaconchaindata
      --slasher-dir /home/.eth2/slasherdata
      --http-address 127.0.0.1
      --http
      --debug-level $LOG_LEVEL
      --slasher
      --slasher-max-db-size 32
      --slasher-broadcast
    network_mode: host
    volumes:
      - ./config:/root/sbc/config
      - ./node_db:/home/.eth2/beaconchaindata
      - ./slasher_db:/home/.eth2/slasherdata
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
  validator-import:
    image: ghcr.io/gnosischain/gbc-lighthouse:latest-unstable
    command: |
      lighthouse account_manager validator import
      --testnet-dir /root/sbc/config
      --password-file /root/sbc/keys/keystore_password.txt
      --reuse-password
      --directory /root/sbc/keys/validator_keys
      --datadir /root/sbc
    volumes:
      - ./config:/root/sbc/config
      - ./keys:/root/sbc/keys
      - ./validators:/root/sbc/validators
  validator:
    image: ghcr.io/gnosischain/gbc-lighthouse:latest-unstable
    command: |
      lighthouse validator_client
      --testnet-dir /root/sbc/config
      --validators-dir /root/sbc/validators
      --beacon-nodes http://localhost:5052
      --graffiti-file=/root/sbc/config/graffiti.yml
    network_mode: host
    volumes:
      - ./config:/root/sbc/config
      - ./validators:/root/sbc/validators
    logging:
      driver: syslog
      options: { tag: '{{.Name}}/{{.ID}}' }
